@AccessControl.authorizationCheck: #NOT_REQUIRED
@Metadata.allowExtensions: true
@EndUserText.label: '###GENERATED Core Data Service Entity'
define view entity ZR_TGRC_ASSET_VAL
  as select from ztgrc_asset_val as AssetVal
  association        to parent ZR_TGRC_ASSET   as _Asset             on $projection.AssetUuid = _Asset.AssetUuid
  association [0..1] to ZR_Asset_Status_PL     as _AssetStatus_PL    on $projection.AssetStatus = _AssetStatus_PL.Id
  association [0..1] to ZR_ASSET_VAL_STATUS_PL as _AssetValStatus_PL on $projection.AssetValueStatus = _AssetValStatus_PL.Id
  association [0..1] to ZR_PI_CLUB_NEW_PL      as _PIClub_PL         on $projection.PIClub = _PIClub_PL.Id
  association [0..1] to ZR_PVST_PL             as _PVST_PL           on $projection.PvSTOnly = _PVST_PL.Id
{

  key asset_uuid                     as AssetUuid,
  key asset_value_uuid               as AssetValueUuid,
      asset_value_external           as AssetValueExternal,
      record_type                    as Recordtype,
      amount_of_interest             as AmountOfInterest,
      amount_of_interest_change_amt  as AmountOfInterestChangeAmt,
      apmm_insured_value             as ApmmInsuredValue,
      asset_value                    as AssetValue,
      asset_category                 as AssetCategory,
      asset_status                   as AssetStatus,
      asset_value_formula            as AssetValueFormula,
      asset_value_onl                as AssetValueOnl,
      asset_value_100_percent        as AssetValue100Percent,
      asset_val_100_percnt_chng_amt  as AssetVal100PercntChngAmt,
      asset_value_change_amount      as AssetValueChangeAmount,
      asset_value_for_interest       as AssetValueForInterest,
      asset_val_for_interestchng_amt as AssetValForInterestchngAmt,
      asset_name                     as AssetName,
      asset_value_status             as AssetValueStatus,
      business_interruption          as BusinessInterruption,
      business_interruption_chng_amt as BusinessInterruptionChngAmt,
      business_unit                  as BusinessUnit,
      cargo_value                    as CargoValue,
      content_equipment              as ContentEquipment,
      cranes_and_handling_equipment  as CranesAndHandlingEquipment,
      cranes_handling_equip_chng_amt as CranesHandlingEquipChngAmt,
      createdb                       as Createdb,
      currency                       as Currency,
      currency_code                  as CurrencyCode,
      deadweight_tonnage             as DeadweightTonnage,
      declared_value                 as DeclaredValue,
      deductible                     as Deductible,
      equipment                      as Equipment,
      flag                           as Flag,
      flag_id                        as FlagId,
      gross_tonnage                  as GrossTonnage,
      hierarchy                      as Hierarchy,
      hull_value                     as HullValue,
      hull_value_change_amount       as HullValueChangeAmount,
      infrastructure                 as Infrastructure,
      lastmodifiedb                  as Lastmodifiedb,
      most_recent                    as MostRecent,
      rk_next_ptr                    as RkNextPtr,
      otli_value                     as OtliValue,
      otli_value_change_amount       as OtliValueChangeAmount,
      hierarchy_node                 as HierarchyNode,
      owner_id                       as OwnerId,
      p_i_club_new                   as PIClubNew,
      p_i_club                       as PIClub,
      rk_prev_ptr                    as RkPrevPtr,
      prop_handling_equip_chng_amt   as PropHandlingEquipChngAmt,
      property                       as Property,
      property_and_handling_equip    as PropertyAndHandlingEquip,
      property_change_amount         as PropertyChangeAmount,
      pv_s_t_only                    as PvSTOnly,
      renewal_assignment             as RenewalAssignment,
      revenue                        as Revenue,
      rk_error_detail                as RkErrorDetail,
      rk_error_flag                  as RkErrorFlag,
      rk_gen_asset_values_pid        as RkGenAssetValuesPid,
      rk_pending_void_count          as RkPendingVoidCount,
      rk_pid_constructor             as RkPidConstructor,
      status                         as Status,
      total_insured_value            as TotalInsuredValue,
      total_insured_value_chng_amt   as TotalInsuredValueChngAmt,
      utilisation                    as Utilisation,
      utilization                    as Utilization,
      utilization_change_amount      as UtilizationChangeAmount,
      valuation_date                 as ValuationDate,
      valuation_end_date             as ValuationEndDate,
      variance_notes                 as VarianceNotes,
      volume_tons                    as VolumeTons,
      war_value                      as WarValue,
      war_value_change_amount        as WarValueChangeAmount,
      warehouse_office_buildings     as WarehouseOfficeBuildings,
      @Semantics.user.createdBy: true
      createdby                      as Createdby,
      @Semantics.systemDateTime.createdAt: true
      createdat                      as Createdat,
      @Semantics.user.localInstanceLastChangedBy: true
      lastchangedby                  as Lastchangedby,
      @Semantics.systemDateTime.localInstanceLastChangedAt: true
      lastchangedat                  as Lastchangedat,
      _Asset,
      _AssetStatus_PL,
      _AssetValStatus_PL,
      _PIClub_PL,
      _PVST_PL

}
